/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.ArregloMedicamentos;
import clases.ListaEnlazada;
import clases.Medicamento;

/**
 *
 * @author Ing. Peña Aviles
 */
public class AgregarMedicamento extends javax.swing.JFrame {

    ListaEnlazada lista = new ListaEnlazada();
//    ArregloMedicamentos arreglo=new ArregloMedicamentos();
//    Medicamento medicamento1 = new Medicamento("PARACETAMOL", 5.40,
//            "medicamento para la gripa", "Panadol",
//            "pastilla", 4, "analgesico", 1044);
//    Medicamento medicamento2 = new Medicamento("CREMA REGENERADORA BEPANTHEN",
//            22.30,
//            "crema para la piel", "Bepanthen",
//            "pomada", 2, "crema", 1041);
//    Medicamento medicamento3 = new Medicamento("CREMA REGENERADORA  ZARIDON", 5.50,
//            "tableta recubierta", "Novalex Pharma",
//            "tableta", 10, "tableta ", 1043);
//    Medicamento[] miArreglo = new Medicamento[3];

    public AgregarMedicamento() {

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
//        miArreglo[0] = medicamento1;
//        miArreglo[1] = medicamento2;
//        miArreglo[2] = medicamento3;
//        lista.insertarArreglo(arreglo.getMiArreglo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreMedicamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precioMedicamento = new javax.swing.JTextField();
        descripcionMedicamento = new javax.swing.JTextField();
        fabricanteMedicamento = new javax.swing.JTextField();
        presentacionMedicamento = new javax.swing.JTextField();
        stockMedicamento = new javax.swing.JTextField();
        tipoMedicamento = new javax.swing.JTextField();
        codigoMedicamento = new javax.swing.JTextField();
        AgregarMedicamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        EliminarInicio = new javax.swing.JButton();
        EliminarFinal = new javax.swing.JButton();
        EliminarCodigo = new javax.swing.JButton();
        codigoEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("AGREGAR");

        jLabel2.setText("Nombre ");

        nombreMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMedicamentoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Nombre del fabricante");

        jLabel6.setText("Tipo de presentacion");

        jLabel7.setText("Stock");

        jLabel8.setText("Tipo de medicamento");

        jLabel9.setText("Codigo");

        AgregarMedicamento.setText("AGREGAR");
        AgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMedicamentoActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("ELIMINAR");

        EliminarInicio.setText("Eliminar medicamento inicial");
        EliminarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarInicioActionPerformed(evt);
            }
        });

        EliminarFinal.setText("Eliminar medicamento final");
        EliminarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarFinalActionPerformed(evt);
            }
        });

        EliminarCodigo.setText("Eliminar por codigo :");
        EliminarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarMedicamento)
                            .addComponent(presentacionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descripcionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fabricanteMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EliminarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(codigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarInicio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(precioMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(EliminarFinal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descripcionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fabricanteMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EliminarCodigo)
                            .addComponent(codigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(presentacionMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(stockMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(codigoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(AgregarMedicamento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMedicamentoActionPerformed

    private void AgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMedicamentoActionPerformed
        txtArea.setText("");
        String nombreMedicamento = this.nombreMedicamento.getText();
        int precioMedicamento = Integer.parseInt(this.precioMedicamento.getText());
        String descripcionMedicamento = this.descripcionMedicamento.getText();
        String fabricanteMedicamento = this.fabricanteMedicamento.getText();
        String presentacionMedicamento = this.presentacionMedicamento.getText();
        int stockMedicamento = Integer.parseInt(this.stockMedicamento.getText());
        String tipoMedicamento = this.tipoMedicamento.getText();
        int codigoMedicamento = Integer.parseInt(this.codigoMedicamento.getText());
        Medicamento medicina = new Medicamento(nombreMedicamento, precioMedicamento, descripcionMedicamento,
                fabricanteMedicamento, presentacionMedicamento, stockMedicamento, tipoMedicamento,
                codigoMedicamento);
        lista.agregarMedicamento(medicina);
        txtArea.append("Nombre" + "\t" + "Precio" + "\t" + "Fabricante" + "\t" + "Stock" + "\t" + "Codigo" + "\t" + "Descripcion" + "\t" + "Presentacion" + "\t" + "Tipo" + "\n");
        txtArea.append(lista.imprimirLista());


    }//GEN-LAST:event_AgregarMedicamentoActionPerformed

    private void EliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarInicioActionPerformed
        lista.eliminarPrimero();
//        System.out.println(lista.obtener(0).getNombre());
        txtArea.setText("");
        txtArea.append("Nombre" + "\t" + "Precio" + "\t" + "Fabricante" + "\t" + "Stock" + "\t" + "Codigo" + "\t" + "Descripcion" + "\t" + "Presentacion" + "\t" + "Tipo" + "\n");
        txtArea.append(lista.imprimirLista());
//        lista.imprimirLista();
    }//GEN-LAST:event_EliminarInicioActionPerformed

    private void EliminarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCodigoActionPerformed
        int codigo = Integer.parseInt(codigoEliminar.getText());
        lista.eliminar(codigo);
//        System.out.println(lista.obtener(0).getNombre());
//        lista.imprimirLista();
        txtArea.setText("");
        txtArea.append("Nombre" + "\t" + "Precio" + "\t" + "Fabricante" + "\t" + "Stock" + "\t" + "Codigo" + "\t" + "Descripcion" + "\t" + "Presentacion" + "\t" + "Tipo" + "\n");

        txtArea.append(lista.imprimirLista());
    }//GEN-LAST:event_EliminarCodigoActionPerformed

    private void EliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarFinalActionPerformed
        lista.eliminarFinal();
        txtArea.setText("");
        txtArea.append("Nombre" + "\t" + "Precio" + "\t" + "Fabricante" + "\t" + "Stock" + "\t" + "Codigo" + "\t" + "Descripcion" + "\t" + "Presentacion" + "\t" + "Tipo" + "\n");

        txtArea.append(lista.imprimirLista());
//        lista.imprimirLista();
    }//GEN-LAST:event_EliminarFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMedicamento;
    private javax.swing.JButton EliminarCodigo;
    private javax.swing.JButton EliminarFinal;
    private javax.swing.JButton EliminarInicio;
    private javax.swing.JTextField codigoEliminar;
    private javax.swing.JTextField codigoMedicamento;
    private javax.swing.JTextField descripcionMedicamento;
    private javax.swing.JTextField fabricanteMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreMedicamento;
    private javax.swing.JTextField precioMedicamento;
    private javax.swing.JTextField presentacionMedicamento;
    private javax.swing.JTextField stockMedicamento;
    private javax.swing.JTextField tipoMedicamento;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
